#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Feb 20 09:55:07 2023

@author: jiayue.yuan
"""

import streamlit as st


st.set_page_config(
    page_title="Home",
    layout="wide",
    initial_sidebar_state="expanded",
    menu_items={
        'Get Help': "mailto:joyyuan89@gmail.com",
        'Report a bug': "mailto:joyyuan89@gmail.com",
        'About': "contact author: Jiayue & Jake"
    }
)

#%% sidebar
st.sidebar.markdown("# ✨About the authors")

st.sidebar.write("Jake Wen")
st.sidebar.write("Jiayue Yuan")
#%%main page


st.markdown("# Home Page 🎈")

#1.introduction
st.markdown("### 1.Introduction")
st.markdown("""
            Welcome to a description of an exciting project that is currently being developed. 
            This project focuses on utilizing transformed based language models to scan and analyze text-based market information. 
            The main objective of the project is to distill information and generate an information hierarchy for analysis.
            The project comprises of four distinct parts, each of which is integral to the overall success of the project. 
            - The first part involves the retrieval of central bank speeches, and analyzing the central bank speeches using keyword analysis to extract important pieces of information.
            - The second part involves tracking keyword trends over time, providing a valuable insight into how market sentiment and conditions change over time.
               Also,a keyword heat map is generated, which provides a visual representation of the central bank speech's most significant keywords. 
               This heat map is particularly useful in identifying trends and patterns in the data, allowing for easier interpretation and analysis.
            - The third part allow users to seach the trend of any topic.
            Overall, this project has the potential to revolutionize the way market information is analyzed, providing valuable insights to businesses and investors alike.
            
            > generated by ChatGPT
            """)
#2. guide for keyword extractor
st.markdown("### Part1. Keyword Extractor")
st.markdown("### Part2. Topic Trend Tracker")
st.markdown("### Part3. Topic Seacher")
st.markdown("### Part4. More...")





